export const ERROR_CODES = {
  NETWORK_ERROR: 'NETWORK_ERROR',
  SERVER_ERROR: 'SERVER_ERROR',

  CONFLICT_EXISTS: 'CONFLICT_EXISTS',
  INVALID_DATA: 'INVALID_DATA',
  UNAUTHORIZED: 'UNAUTHORIZED',

  MISSING_FIELDS: 'MISSING_FIELDS',
};
